### ISSUE TITLE
Use wp-cli to configure?

### ISSUE THREAD

**Issue by berique** [angelo-v/wordpress-backup#10]
How about using [wp-cli](http://wp-cli.org/) to configure the wordpress??? The user could implement his own "wp-cli.yml" to uninstall, define hostname and etc.

Especially in case of import external sites for dev using docker.

How about it?

**Comment by angelo-v** [comment]
Sounds interesting, I did not know this, yet.
But wouldn't this be something the wordpress container should use, and not the wordpress-backup container?

**Comment by berique** [comment]
Yeah... I think you're right, It's better be at a wordpress container than at the wordpress-backup.

Thanks very much
