### ISSUE TITLE
Latest ubuntu build don't ship cron

### ISSUE THREAD

**Issue by Guibod** [angelo-v/wordpress-backup#11]
You need to:
RUN apt-get update && \
    apt-get install mysql-client cron -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/\* && \
    mkdir /backups

**Comment by ppetru** [comment]
bzip2 also - PR #12 is what it took to fix this for me.

**Comment by angelo-v** [comment]
Thanks for your feedback and contribution!
