### ISSUE TITLE
The Hostname of the SQL Server is hardcoded to mysql

### ISSUE THREAD

**Issue by maglite4cell** [angelo-v/wordpress-backup#17]
Can we make that Enviornment Variable?

**Comment by angelo-v** [comment]
What is your use-case for this? wordpress-backup, wordpress and mysql should reside in one docker network on its own, see [wordpress-docker-quickstart](https://github.com/angelo-v/wordpress-backup-quickstart/blob/master/docker-compose.yml) for an example. Why is there a need to use a different name?

If you need to reach mysql on other names, you can use [network aliases](https://docs.docker.com/compose/compose-file/#aliases).

But perhaps I am missing something, so let me know, if this does not work out for you.

**Comment by cbarlow1993** [comment]
It would be great to have it as an environmental variable. A couple of reasons from me: 

- I can run a single backup container and through the command line, backup multiple wordpress instances running on the same host. I cant have multiple services called mysql but I would like to inject the container name as a variable.

- It keeps the code cleaner than having to include a network aliases.
