### ISSUE TITLE
Error: MYSQL_ENV_MYSQL_USER not set

### ISSUE THREAD

**Issue by javaknight** [angelo-v/wordpress-backup#2]
Getting this error... where do I need to start looking..?

**Comment by angelo-v** [comment]
What exactly did you try to do, when this error occurred? What is your container setup? Did you specify MYSQL_USER for your mysql container as described in the README?

**Comment by javaknight** [comment]
I retraced my steps from the beginning and I'm not sure what I did wrong, but this time, everything worked just fine. Sorry.
