### ISSUE TITLE
backup script is stopping before the end

### ISSUE THREAD

**Issue by kasty** [angelo-v/wordpress-backup#25]
Hello,
I have a problem using your wordpress backup.
When running the backup script it's stopping before the end, the db archive is not created :

```
root@myhost# docker exec -it backup-container bash
root@f586c32ad7e9:/# bash backup
```

The log is ending on :

```
...
-rwxrwxr-x www-data/www-data      238 2019-05-21 13:26 ./wp-admin/ms-options.php
-rwxrwxr-x www-data/www-data     6320 2019-05-21 13:26 ./wp-admin/plugin-install.php
-rwxrwxr-x www-data/www-data      369 2019-05-21 13:26 ./wp-blog-header.php
```

When running throw the Makefile that is on my host the script runs well till the end :
(extract of my Makefile)
```
backup:
	docker exec backup-container backup
```

Any idea ?
Thanks for your work !

**Comment by angelo-v** [comment]
No error message? Sounds weird... What is the exit code of `bash backup`?

**Comment by kasty** [comment]
It appears that the error is aleatory, sometimes the scripts ends well, sometimes not. When it's not exit code is "1" :
```
bash backup
[....]
-rwxrwxr-x www-data/www-data      238 2019-05-21 13:26 ./wp-admin/ms-options.php
-rwxrwxr-x www-data/www-data     6320 2019-05-21 13:26 ./wp-admin/plugin-install.php
-rwxrwxr-x www-data/www-data      369 2019-05-21 13:26 ./wp-blog-header.php
root@f586c32ad7e9:/# echo $?
1
```

When successfull :
```
bash backup
[....]
-rwxrwxr-x www-data/www-data      238 2019-05-21 13:26 ./wp-admin/ms-options.php
-rwxrwxr-x www-data/www-data     6320 2019-05-21 13:26 ./wp-admin/plugin-install.php
-rwxrwxr-x www-data/www-data      369 2019-05-21 13:26 ./wp-blog-header.php
creating database dump
mysqldump: [Warning] Using a password on the command line interface can be insecure.
Finished: SUCCESS
root@f586c32ad7e9:/# echo $?
0
```

**Comment by angelo-v** [comment]
aha, ok. From `man tar`:

> this exit code means that some files were changed while being archived and so the resulting archive does not contain the exact copy of the file set.

I am not yet sure if and how I should handle that in wordpress-backup. I guess it might be a problem for sites that have really frequent updates. If this is not the case for you, try perfoming the backup during a "silent" period.

**Comment by kasty** [comment]
Mhh I see but that's strange, I don't see which files could be changed while archiving. Automated backups are already made during a "silent" period (at 3am).

I could find this warning but it doen't help me much : 
`tar: ./wp-content: file changed as we read it`

For the moment I added `--ignore-failed-read` option to the tar command, I'll try this during a few days and I'll see...

Thanks for your help

**Comment by angelo-v** [comment]
mhh, have you installed any plugins that change wp-content folder? Could you detect what exactly is changed there?
