### ISSUE TITLE
Update from 5.7.30 to 5.7.31--> Access denied

### ISSUE THREAD

**Issue by mathsen** [angelo-v/wordpress-backup#29]
Since the mysql update from 5.7.30 to 5.7.31 the backup script throws the following error, when executing the mysqldump statement:

> mysqldump: Error: 'Access denied; you need (at least one of) the PROCESS privilege(s) for this operation' when trying to dump tablespaces

Also see [the official release notes](https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-31.html) and [this blog post](https://dan.langille.org/2020/07/21/mysqldump-error-access-denied-you-need-at-least-one-of-the-process-privileges-for-this-operation-when-trying-to-dump-tablespaces/).
As denoted [here](https://forums.cpanel.net/threads/cpanel-33473-mysql-dump-process-privilege-error-after-5-7-31-update.675657/) I proposa adding the "--no-tablespaces" option.

**Comment by angelo-v** [comment]
Thanks for the report and the fix. Can you confirm it works again?

**Comment by mathsen** [comment]
Yes, I can confirm, it works again! And thank you for this repository!
