### ISSUE TITLE
[Question] Sync backup on an Object Storage DB

### ISSUE THREAD

**Issue by sasadangelo** [angelo-v/wordpress-backup#31]
Hi,

First of all, thank you for your project.
I created a simple project where I customize a .env file and with docker-compose I create a WordPress website running on docker using MySQL, WordPress, Nginx-proxy (as a reverse proxy to access my websites on 80/443 port).
https://github.com/sasadangelo/webagency

Now I want to add a backup container. However, my understanding is that the backup is saved on a local volume I attach to the container. I am not an expert, but it would be helpful to have a system that saves these backups on S3 Object Storage, Dropbox, or other 3rdparty services.

I noticed there are several projects on the web, however, most of them simply sync the backup volumes with S3, for example. It would be better to have a container that keeps max N file in local (for example 5) and the rest on Object Storage. Moreover, it should have a sort of retention policy to say: keep only the latest N backup on S3.

Do you know if there is a project for that combined with your project meet these requirements?

**Comment by angelo-v** [comment]
Yes, wordpress-backup simply uses a docker volume for the storage and it is out of scope of this project to do more than that. But you could sync this volume with other services as you like.

A retention policy could be a nice improvement of wordpress-backup but I am not planning to implement it currently. You could help yourself with a cron triggered cleanup script for example as a workarround.

Sorry, I cannot recommend any tool. If you find something let me know, I can add it to the readme then.

**Comment by sasadangelo** [comment]
Thank you for your reply.
