### ISSUE TITLE
File in use when trying to restore from backup

### ISSUE THREAD

**Issue by Ohmslaw79** [angelo-v/wordpress-backup#34]
Whenever I try to restore from backup I get this error

```root@4b094ce1d387:/# restore 20220815
deleting files from /var/www/html/
rm: cannot remove '/var/www/html/wp-content': Device or resource busy```

I have tried stopping the Wordpress container and have gotten nothing. Any ideas why this would still be in use?

**Comment by angelo-v** [comment]
I cannot tell. Perhaps if you give me more details about your configuration (docker-compose.yml, commands you used to start / stop the containers etc) Are there other containers or the host using the /var/www/html volume?
