### ISSUE TITLE
Cleanup solution

### ISSUE THREAD

**Issue by j3k0** [angelo-v/wordpress-backup#5]
Hello,

This docker image is nice, a missing feature is that daily backups are never deleted: so this will just grow forever.

Did you happen to implement a solution to this, like a separate script to do some cleanup?

Alternatively, maybe an even cooler solution to this would be to implement incremental backup with tar. https://www.gnu.org/software/tar/manual/html_section/tar_40.html Just saying!

Thanks again for the great image :+1:

**Comment by angelo-v** [comment]
Thanks for the feedback. I like your ideas, but I am currently not developing it further. Feel free to fork and send me a pull request.

**Comment by j3k0** [comment]
PR sent.

In the meantime I setup my own fork to build the "jeko/wordpress-backup" image (in case anyone is interested).

**Comment by angelo-v** [comment]
Great thanks. I will have a look at your requests as soon as I find the time.

**Comment by angelo-v** [comment]
Cleanup solution for old backups implemented.
