### ISSUE TITLE
Step 2 in Migrate blog to Docker Container

### ISSUE THREAD

**Issue by khoi-thinh** [angelo-v/wordpress-backup#9]
Hi everyone.
I followed the tutorial and it worked. The problem is, I'm running and testing on Centos7 which is installed on Amazon EC2. After reboot instance and log in, i was not be able to restore back up.
It said;
Error response from daemon: Container wordpress-backup is not running
How should i do? If i run the wordpress-backup images, what would be the next step???

**Comment by angelo-v** [comment]
The wordpress backup container must be running. Use 'docker start wordpress-backup'

I recommend the 'restart: always' policy on container creation, so that containers start automatically after rebooting the docker host
